In [181]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("Import all the libraries")

Import all the libraries

In [182]:
DATA_DIR = r"C:\WORK\Data Analysis Projects\Job Market Data Analysis Project (Naukari.com)\Datasets\naukri_com-job_sample.csv"

In [183]:
df=pd.read_csv(DATA_DIR)

In [184]:
df.head()

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4

In [185]:
df.shape

(22000, 14)

In [186]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              21996 non-null  str
 1   education            20004 non-null  str
 2   experience           21996 non-null  str
 3   industry             21995 non-null  str
 4   jobdescription       21996 non-null  str
 5   jobid                22000 non-null  int64
 6   joblocation_address  21499 non-null  str
 7   jobtitle             22000 non-null  str
 8   numberofpositions    4464 non-null   float64
 9   payrate              21903 non-null  str
 10  postdate             21977 non-null  str
 11  site_name            3987 non-null   str
 12  skills               21472 non-null  str
 13  uniq_id              22000 non-null  str
dtypes: float64(1), int64(1), str(12)
memory usage: 2.3 MB

In [187]:
df.isnull().sum()

company                    4
education               1996
experience                 4
industry                   5
jobdescription             4
jobid                      0
joblocation_address      501
jobtitle                   0
numberofpositions      17536
payrate                   97
postdate                  23
site_name              18013
skills                   528
uniq_id                    0
dtype: int64

In [188]:
df.duplicated().sum()

np.int64(0)

In [189]:
missing_values = df.isnull().sum()

missing_values

company                    4
education               1996
experience                 4
industry                   5
jobdescription             4
jobid                      0
joblocation_address      501
jobtitle                   0
numberofpositions      17536
payrate                   97
postdate                  23
site_name              18013
skills                   528
uniq_id                    0
dtype: int64

In [190]:
percentage_missing = missing_values*100/len(df)
percentage_missing

company                 0.018182
education               9.072727
experience              0.018182
industry                0.022727
jobdescription          0.018182
jobid                   0.000000
joblocation_address     2.277273
jobtitle                0.000000
numberofpositions      79.709091
payrate                 0.440909
postdate                0.104545
site_name              81.877273
skills                  2.400000
uniq_id                 0.000000
dtype: float64

In [191]:
missing_values_df = pd.DataFrame({"Count_Missing":missing_values,
                                  "Percentage_Missing":percentage_missing})

In [192]:
missing_values_df

                     Count_Missing  Percentage_Missing
company                          4            0.018182
education                     1996            9.072727
experience                       4            0.018182
industry                         5            0.022727
jobdescription                   4            0.018182
jobid                            0            0.000000
joblocation_address            501            2.277273
jobtitle                         0            0.000000
numberofpositions            17536           79.709091
payrate                         97            0.440909
postdate                        23            0.104545
site_name                    18013           81.877273
skills                         528            2.400000
uniq_id                          0            0.000000

In [193]:
df.columns

Index(['company', 'education', 'experience', 'industry', 'jobdescription',
       'jobid', 'joblocation_address', 'jobtitle', 'numberofpositions',
       'payrate', 'postdate', 'site_name', 'skills', 'uniq_id'],
      dtype='str')

In [194]:
for col in df.columns:
    print("{} has {} values".format(col,df[col].nunique()))

company has 8469 values
education has 2355 values
experience has 147 values
industry has 63 values
jobdescription has 21063 values
jobid has 21910 values
joblocation_address has 2329 values
jobtitle has 17564 values
numberofpositions has 84 values
payrate has 1848 values
postdate has 4203 values
site_name has 1 values
skills has 45 values
uniq_id has 22000 values

In [195]:
unique = []

for col in df.columns:
    unique.append([col,df[col].nunique(),df[col].unique])

In [196]:
unique

[['company',
  8469,
  <bound method Series.unique of 0                                        MM Media Pvt Ltd
  1                                      find live infotech
  2                     Softtech Career Infosystem Pvt. Ltd
  3                                  Onboard HRServices LLP
  4              Spire Technologies and Solutions Pvt. Ltd.
                                 ...
  21995         Morgan Stanley Advantage Services Pvt. Ltd.
  21996    Careernet Technologies Pvt Ltd hiring for Client
  21997                                      Musk - Startup
  21998                                        Confidential
  21999                     Cambio Consulting India Pvt Ltd
  Name: company, Length: 22000, dtype: str>],
 ['education',
  2355,
  <bound method Series.unique of 0        UG: B.Tech/B.E. - Any Specialization PG:Any Po...
  1        UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...
  2        UG: Any Graduate - Any Specialization PG:Any P...
  3        UG: Any Graduate - Any Specialization PG:CA Do...
  4        UG: B.Tech/B.E. - Any Specialization PG:Any Po...
                                 ...
  21995                UG: Any Graduate - Any Specialization
  21996    UG: B.Tech/B.E. - Any Specialization PG:M.Tech...
  21997    UG: B.Tech/B.E. - Any Specialization PG:Any Po...
  21998    UG: B.Tech/B.E. - Any Specialization PG:MCA - ...
  21999    UG: B.Tech/B.E. - Any Specialization PG:MCA - ...
  Name: education, Length: 22000, dtype: str>],
 ['experience',
  147,
  <bound method Series.unique of 0          0 - 1 yrs
  1          0 - 0 yrs
  2          4 - 8 yrs
  3        11 - 15 yrs
  4          6 - 8 yrs
              ...
  21995     9 - 13 yrs
  21996      3 - 5 yrs
  21997      2 - 4 yrs
  21998     7 - 12 yrs
  21999     5 - 10 yrs
  Name: experience, Length: 22000, dtype: str>],
 ['industry',
  63,
  <bound method Series.unique of 0                Media / Entertainment / Internet
  1        Advertising / PR / MR / Event Management
  2                 IT-Software / Software Services
  3          Banking / Financial Services / Broking
  4                 IT-Software / Software Services
                             ...
  21995      Banking / Financial Services / Broking
  21996             IT-Software / Software Services
  21997                        Internet / Ecommerce
  21998             IT-Software / Software Services
  21999             IT-Software / Software Services
  Name: industry, Length: 22000, dtype: str>],
 ['jobdescription',
  21063,
  <bound method Series.unique of 0        Job Description   Send me Jobs like this Quali...
  1        Job Description   Send me Jobs like this Quali...
  2        Job Description   Send me Jobs like this - as ...
  3        Job Description   Send me Jobs like this - Inv...
  4        Job Description   Send me Jobs like this Pleas...
                                 ...
  21995    Job Description   Send me Jobs like this Greet...
  21996    Job Description   Send me Jobs like this Looki...
  21997    Job Description   Send me Jobs like this Work ...
  21998    Job Description   Send me Jobs like this We ar...
  21999    Job Description   Send me Jobs like this Job d...
  Name: jobdescription, Length: 22000, dtype: str>],
 ['jobid',
  21910,
  <bound method Series.unique of 0        210516002263
  1        210516002391
  2        101016900534
  3         81016900536
  4        120916002122
               ...
  21995    241116007152
  21996    241116001104
  21997    251116900644
  21998    231116901329
  21999    251116003840
  Name: jobid, Length: 22000, dtype: int64>],
 ['joblocation_address',
  2329,
  <bound method Series.unique of 0                                                  Chennai
  1                                                  Chennai
  2                                                Bengaluru
  3        Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...
  4                                                Bengaluru
                                 ...
  21995                                            Bengaluru
  21996                                   Bengaluru, Gurgaon
  21997                                            Bengaluru
  21998                                 Delhi NCR, Bengaluru
  21999                                            Bengaluru
  Name: joblocation_address, Length: 22000, dtype: str>],
 ['jobtitle',
  17564,
  <bound method Series.unique of 0                 Walkin Data Entry Operator (night Shift)
  1                       Work Based Onhome Based Part Time.
  2                                   Pl/sql Developer - SQL
  3                   Manager/ad/partner - Indirect Tax - CA
  4                          JAVA Technical Lead (6-8 yrs) -
                                 ...
  21995    Quality Assurance - VP with Morgan Stanley Ban...
  21996        Java Backend Developers for a Product Company
  21997                      Full Stack Development Engineer
  21998    Sr UI Developer/ Technical Lead - Html/ CSS/ J...
  21999                                RF Firmware Engineers
  Name: jobtitle, Length: 22000, dtype: str>],
 ['numberofpositions',
  84,
  <bound method Series.unique of 0         NaN
  1        60.0
  2         NaN
  3         NaN
  4         4.0
           ...
  21995     2.0
  21996     NaN
  21997     NaN
  21998     NaN
  21999     NaN
  Name: numberofpositions, Length: 22000, dtype: float64>],
 ['payrate',
  1848,
  <bound method Series.unique of 0               1,50,000 - 2,25,000 P.A
  1        1,50,000 - 2,50,000 P.A. 20000
  2            Not Disclosed by Recruiter
  3            Not Disclosed by Recruiter
  4            Not Disclosed by Recruiter
                        ...
  21995        Not Disclosed by Recruiter
  21996          8,50,000 - 14,00,000 P.A
  21997        Not Disclosed by Recruiter
  21998        Not Disclosed by Recruiter
  21999         12,00,000 - 22,00,000 P.A
  Name: payrate, Length: 22000, dtype: str>],
 ['postdate',
  4203,
  <bound method Series.unique of 0        2016-05-21 19:30:00 +0000
  1        2016-05-21 19:30:00 +0000
  2        2016-10-13 16:20:55 +0000
  3        2016-10-13 16:20:55 +0000
  4        2016-10-13 16:20:55 +0000
                     ...
  21995    2016-11-25 22:47:05 +0000
  21996    2016-11-24 22:47:05 +0000
  21997    2016-11-25 22:47:05 +0000
  21998    2016-11-27 22:47:05 +0000
  21999    2016-11-25 22:47:05 +0000
  Name: postdate, Length: 22000, dtype: str>],
 ['site_name',
  1,
  <bound method Series.unique of 0                   NaN
  1                   NaN
  2                   NaN
  3                   NaN
  4                   NaN
                ...
  21995    www.naukri.com
  21996    www.naukri.com
  21997    www.naukri.com
  21998    www.naukri.com
  21999    www.naukri.com
  Name: site_name, Length: 22000, dtype: str>],
 ['skills',
  45,
  <bound method Series.unique of 0                                         ITES
  1                                    Marketing
  2        IT Software - Application Programming
  3                                     Accounts
  4        IT Software - Application Programming
                           ...
  21995               IT Software - QA & Testing
  21996    IT Software - Application Programming
  21997    IT Software - Application Programming
  21998    IT Software - Application Programming
  21999         IT Software - System Programming
  Name: skills, Length: 22000, dtype: str>],
 ['uniq_id',
  22000,
  <bound method Series.unique of 0        43b19632647068535437c774b6ca6cf8
  1        d4c72325e57f89f364812b5ed5a795f0
  2        c47df6f4cfdf5b46f1fd713ba61b9eba
  3        115d28f140f694dd1cc61c53d03c66ae
  4        a12553fc03bc7bcced8b1bb8963f97b4
                         ...
  21995    ef40136e3b0c0abdab695d979a4b7153
  21996    acb80b7bb109fa76d22d1f11c6e16c6a
  21997    f6f2885a6c87572616fb766029a0d284
  21998    c6f6538cb1007dd02c1b4b77909b3d38
  21999    74fec26df6e1c0be0171311a2f03f180
  Name: uniq_id, Length: 22000, dtype: str>]]

In [197]:
unique_df = [[col,df[col].nunique(),df[col].unique()] for col in df.columns]

In [198]:
pd.DataFrame(unique_df,columns=["col_name","count","unique"])

,col_name,count,unique
0,company,8469,"[MM Media Pvt Ltd, find live infotech, Softtec..."
1,education,2355,[UG: B.Tech/B.E. - Any Specialization PG:Any P...
2,experience,147,"[0 - 1 yrs, 0 - 0 yrs, 4 - 8 yrs, 11 - 15 yrs,..."
3,industry,63,"[Media / Entertainment / Internet, Advertising..."
4,jobdescription,21063,[Job Description Send me Jobs like this Qual...
5,jobid,21910,"[210516002263, 210516002391, 101016900534, 810..."
6,joblocation_address,2329,"[Chennai, Bengaluru, Mumbai, Bengaluru, Kolkat..."
7,jobtitle,17564,"[Walkin Data Entry Operator (night Shift), Wor..."
8,numberofpositions,84,"[nan, 60.0, 4.0, 2.0, 20.0, 3.0, 1.0, 700.0, 8..."
9,payrate,1848,"[1,50,000 - 2,25,000 P.A, 1,50,000 - 2,50,000 ..."
10,postdate,4203,"[2016-05-21 19:30:00 +0000, 2016-10-13 16:20:5..."
11,site_name,1,"[nan, www.naukri.com]"
12,skills,45,"[ITES, Marketing, IT Software - Application Pr..."
13,uniq_id,22000,"[43b19632647068535437c774b6ca6cf8, d4c72325e57..."

In [199]:
df.columns

Index(['company', 'education', 'experience', 'industry', 'jobdescription',
       'jobid', 'joblocation_address', 'jobtitle', 'numberofpositions',
       'payrate', 'postdate', 'site_name', 'skills', 'uniq_id'],
      dtype='str')

In [200]:
df["payrate"].head(20)

0                               1,50,000 - 2,25,000 P.A
1                        1,50,000 - 2,50,000 P.A. 20000
2                            Not Disclosed by Recruiter
3                            Not Disclosed by Recruiter
4                            Not Disclosed by Recruiter
5                            Not Disclosed by Recruiter
6                               3,00,000 - 6,50,000 P.A
7                            Not Disclosed by Recruiter
8                               1,00,000 - 2,00,000 P.A
9                            Not Disclosed by Recruiter
10                           Not Disclosed by Recruiter
11                           Not Disclosed by Recruiter
12                              1,75,000 - 2,50,000 P.A
13                           Not Disclosed by Recruiter
14                           Not Disclosed by Recruiter
15                           Not Disclosed by Recruiter
16    1,00,000 - 2,00,000 P.A. incentives for achiev...
17                              1,00,000 - 5,00,000 P.A
18                           Not Disclosed by Recruiter
19                           Not Disclosed by Recruiter
Name: payrate, dtype: str

In [201]:
# Min_Payrate
df["payrate"][0].split("-")[0]

'1,50,000 '

In [202]:
#Max_Payrate
df["payrate"][0].split("-")[1]

' 2,25,000 P.A'

In [203]:
len_pay = []
for pay in df["payrate"]:
    len_pay.append(len(str(pay).split("-")))

In [204]:
pd.Series(len_pay).value_counts()

1    17028
2     4682
4      126
3       83
5       54
6       24
7        3
Name: count, dtype: int64

In [205]:
payrate_split = df["payrate"].str.split("-",expand=True)

In [206]:
payrate_split

,0,1,2,3,4,5,6
0,"1,50,000","2,25,000 P.A",NaN,NaN,NaN,NaN,NaN
1,"1,50,000","2,50,000 P.A. 20000",NaN,NaN,NaN,NaN,NaN
2,Not Disclosed by Recruiter,NaN,NaN,NaN,NaN,NaN,NaN
3,Not Disclosed by Recruiter,NaN,NaN,NaN,NaN,NaN,NaN
4,Not Disclosed by Recruiter,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
21995,Not Disclosed by Recruiter,NaN,NaN,NaN,NaN,NaN,NaN
21996,"8,50,000","14,00,000 P.A",NaN,NaN,NaN,NaN,NaN
21997,Not Disclosed by Recruiter,NaN,NaN,NaN,NaN,NaN,NaN
21998,Not Disclosed by Recruiter,NaN,NaN,NaN,NaN,NaN,NaN
21999,"12,00,000","22,00,000 P.A",NaN,NaN,NaN,NaN,NaN

In [207]:
payrate_split[0][0] #There is some Space present, so we have to strip it out

'1,50,000 '

In [208]:
payrate_split[0]=payrate_split[0].str.strip()

In [209]:
payrate_split[0]=payrate_split[0].str.replace(",","")

In [210]:
payrate_split[0]

0                            150000
1                            150000
2        Not Disclosed by Recruiter
3        Not Disclosed by Recruiter
4        Not Disclosed by Recruiter
                    ...
21995    Not Disclosed by Recruiter
21996                        850000
21997    Not Disclosed by Recruiter
21998    Not Disclosed by Recruiter
21999                       1200000
Name: 0, Length: 22000, dtype: str

In [211]:
pd.to_numeric(payrate_split[0],errors='coerce')

0         150000.0
1         150000.0
2              NaN
3              NaN
4              NaN
           ...
21995          NaN
21996     850000.0
21997          NaN
21998          NaN
21999    1200000.0
Name: 0, Length: 22000, dtype: float64

In [212]:
payrate_split[1]=payrate_split[1].str.strip()

In [213]:
payrate_split[1]

0               2,25,000 P.A
1        2,50,000 P.A. 20000
2                        NaN
3                        NaN
4                        NaN
                ...
21995                    NaN
21996          14,00,000 P.A
21997                    NaN
21998                    NaN
21999          22,00,000 P.A
Name: 1, Length: 22000, dtype: str

In [214]:
payrate_split[0]=payrate_split[0].str.replace(",","")

In [215]:
payrate_split[1]

0               2,25,000 P.A
1        2,50,000 P.A. 20000
2                        NaN
3                        NaN
4                        NaN
                ...
21995                    NaN
21996          14,00,000 P.A
21997                    NaN
21998                    NaN
21999          22,00,000 P.A
Name: 1, Length: 22000, dtype: str

In [216]:
payrate_split[1][0]
# Now we will use regular expression to extract only numeric values from the text # As it also contains P.A

'2,25,000 P.A'

In [217]:
payrate_split[1]=payrate_split[1].str.replace(",","")

In [218]:
payrate_split[1]

0               225000 P.A
1        250000 P.A. 20000
2                      NaN
3                      NaN
4                      NaN
               ...
21995                  NaN
21996          1400000 P.A
21997                  NaN
21998                  NaN
21999          2200000 P.A
Name: 1, Length: 22000, dtype: str

In [219]:
pattern = "\D.*"
payrate_split[1]=payrate_split[1].str.replace(pattern,"",regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\vinay pratap singh\AppData\Local\Temp\ipykernel_21636\75164378.py:1: SyntaxWarning: invalid escape sequence '\D'
  pattern = "\D.*"

In [220]:
payrate_split[1]

0         225000
1         250000
2            NaN
3            NaN
4            NaN
          ...
21995        NaN
21996    1400000
21997        NaN
21998        NaN
21999    2200000
Name: 1, Length: 22000, dtype: str

In [221]:
payrate_split

                                0        1    2    3    4    5    6
0                          150000   225000  NaN  NaN  NaN  NaN  NaN
1                          150000   250000  NaN  NaN  NaN  NaN  NaN
2      Not Disclosed by Recruiter      NaN  NaN  NaN  NaN  NaN  NaN
3      Not Disclosed by Recruiter      NaN  NaN  NaN  NaN  NaN  NaN
4      Not Disclosed by Recruiter      NaN  NaN  NaN  NaN  NaN  NaN
...                           ...      ...  ...  ...  ...  ...  ...
21995  Not Disclosed by Recruiter      NaN  NaN  NaN  NaN  NaN  NaN
21996                      850000  1400000  NaN  NaN  NaN  NaN  NaN
21997  Not Disclosed by Recruiter      NaN  NaN  NaN  NaN  NaN  NaN
21998  Not Disclosed by Recruiter      NaN  NaN  NaN  NaN  NaN  NaN
21999                     1200000  2200000  NaN  NaN  NaN  NaN  NaN

[22000 rows x 7 columns]

In [222]:
payrate_split.dtypes

0    str
1    str
2    str
3    str
4    str
5    str
6    str
dtype: object

In [223]:
payrate_split[0] = pd.to_numeric(payrate_split[0],errors="coerce")
payrate_split[1] = pd.to_numeric(payrate_split[1],errors="coerce")

In [224]:
payrate_split.dtypes

0    float64
1    float64
2        str
3        str
4        str
5        str
6        str
dtype: object

In [225]:
df["min_pay"]=payrate_split[0]
df["max_pay"]=payrate_split[1]

In [226]:
df.head()

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id,min_pay,max_pay
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8,150000.0,225000.0
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae,NaN,NaN
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4,NaN,NaN

#### Clean the experience feature

In [227]:
df["experience"].head(20)

0       0 - 1 yrs
1       0 - 0 yrs
2       4 - 8 yrs
3     11 - 15 yrs
4       6 - 8 yrs
5       2 - 5 yrs
6       1 - 3 yrs
7       2 - 7 yrs
8       1 - 3 yrs
9       1 - 5 yrs
10      1 - 3 yrs
11      4 - 8 yrs
12      2 - 4 yrs
13      3 - 8 yrs
14      1 - 5 yrs
15      5 - 7 yrs
16      1 - 2 yrs
17      2 - 4 yrs
18     5 - 10 yrs
19      0 - 1 yrs
Name: experience, dtype: str

In [228]:
df["experience"].value_counts().head(30)

experience
2 - 7 yrs      1712
2 - 5 yrs      1231
3 - 8 yrs      1192
3 - 5 yrs      1181
5 - 10 yrs     1084
1 - 3 yrs       755
2 - 4 yrs       729
4 - 9 yrs       715
0 - 5 yrs       654
3 - 6 yrs       613
1 - 6 yrs       591
0 - 3 yrs       556
10 - 15 yrs     517
0 - 1 yrs       509
5 - 8 yrs       499
1 - 5 yrs       498
0 - 2 yrs       481
1 - 2 yrs       477
6 - 11 yrs      469
2 - 3 yrs       454
4 - 6 yrs       420
4 - 8 yrs       408
1 - 4 yrs       401
2 - 6 yrs       391
5 - 7 yrs       377
7 - 12 yrs      328
3 - 7 yrs       319
8 - 13 yrs      311
4 - 7 yrs       296
8 - 10 yrs      270
Name: count, dtype: int64

In [229]:
exp_split = df["experience"].str.split("-",expand=True)

In [230]:
exp_split

         0        1    2
0       0     1 yrs  NaN
1       0     0 yrs  NaN
2       4     8 yrs  NaN
3      11    15 yrs  NaN
4       6     8 yrs  NaN
...    ...      ...  ...
21995   9    13 yrs  NaN
21996   3     5 yrs  NaN
21997   2     4 yrs  NaN
21998   7    12 yrs  NaN
21999   5    10 yrs  NaN

[22000 rows x 3 columns]

In [231]:
exp_split[0] = exp_split[0].str.strip()

In [232]:
exp_split[1] = exp_split[1].str.strip()

In [233]:
exp_split[1] = exp_split[1].str.replace("yrs","")

In [234]:
exp_split

        0    1    2
0       0   1   NaN
1       0   0   NaN
2       4   8   NaN
3      11  15   NaN
4       6   8   NaN
...    ..  ...  ...
21995   9  13   NaN
21996   3   5   NaN
21997   2   4   NaN
21998   7  12   NaN
21999   5  10   NaN

[22000 rows x 3 columns]

In [235]:
exp_split.dtypes

0    str
1    str
2    str
dtype: object

In [236]:
exp_split[0] = pd.to_numeric(exp_split[0],errors="coerce")
exp_split[1] = pd.to_numeric(exp_split[1],errors="coerce")

In [237]:
exp_split.dtypes

0    float64
1    float64
2        str
dtype: object

In [238]:
exp_split

          0     1    2
0       0.0   1.0  NaN
1       0.0   0.0  NaN
2       4.0   8.0  NaN
3      11.0  15.0  NaN
4       6.0   8.0  NaN
...     ...   ...  ...
21995   9.0  13.0  NaN
21996   3.0   5.0  NaN
21997   2.0   4.0  NaN
21998   7.0  12.0  NaN
21999   5.0  10.0  NaN

[22000 rows x 3 columns]

In [239]:
df["min_exp"] = exp_split[0]
df["max_exp"] = exp_split[1]

In [240]:
df.head(20)

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id,min_pay,max_pay,min_exp,max_exp
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8,150000.0,225000.0,0.0,1.0
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0,0.0,0.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN,4.0,8.0
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae,NaN,NaN,11.0,15.0
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4,NaN,NaN,6.0,8.0
5,PFS Web Global Services Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:MCA - ...,2 - 5 yrs,IT-Software / Software Services,Job Description Send me Jobs like this We ar...,131016005070,Bengaluru,WALK IN - As400 Developer - Pfsweb Global Serv...,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,8c3af9062ea835b0965779e2c7faac76,NaN,NaN,2.0,5.0
6,Kinesis Management Consultant Pvt. Ltd,NaN,1 - 3 yrs,IT-Software / Software Services,Job Description Send me Jobs like this exper...,131016004451,"Delhi NCR, Mumbai, Bengaluru, Kochi, Greater N...",PHP Developer,2.0,"3,00,000 - 6,50,000 P.A",2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,98f84958cd6409386e7f0c9e447b8510,300000.0,650000.0,1.0,3.0
7,Agile HR consultancy Pvt. Ltd. hiring for Ross...,"UG: Diploma - Any Specialization, Electrical, ...",2 - 7 yrs,Aviation / Aerospace Firms,Job Description Send me Jobs like this Job D...,121016002995,Bengaluru,Member Technical Staff-wire Harness/cable Harn...,20.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Production,c811c10568fdbfdb3d5e633c99c914b4,NaN,NaN,2.0,7.0
8,HANSUM INDIA ELECTRONICS PVT.LTD.,"UG: Diploma - Any Specialization, Electronics/...",1 - 3 yrs,Industrial Products / Heavy Machinery,Job Description Send me Jobs like this Indep...,131016002120,Bengaluru,Team Leader,2.0,"1,00,000 - 2,00,000 P.A",2016-10-13 16:20:55 +0000,NaN,Production,a40cb270401af0c246dbe60dcf219262,100000.0,200000.0,1.0,3.0
9,Accenture,UG: Any Graduate - Any Specialization PG:Any P...,1 - 5 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Overa...,121016901354,Bengaluru,German Translator,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,ITES,7774df1c672c0b92486da8b36a721638,NaN,NaN,1.0,5.0
10,Premium,UG: Any Graduate - Any Specialization PG:Any P...,1 - 3 yrs,FMCG / Foods / Beverage,Job Description Send me Jobs like this LimeT...,101016001508,"Mumbai, Delhi, Bengaluru",Business Development Manager,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Sales,8ad928aef950cd1bbc1c02d72898df47,NaN,NaN,1.0,3.0
11,Convate hiring for Retail/e-commerce domain,UG: Any Graduate - Any Specialization,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Greet...,61016003187,Bengaluru,Opening for Android Developer-bangalore-4-8 yrs,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,2657f737cb46cf289a05d6577a746976,NaN,NaN,4.0,8.0
12,Sinai Global,"UG: B.Tech/B.E. - Any Specialization, Diploma ...",2 - 4 yrs,IT-Software / Software Services,Job Description Send me Jobs like this We ar...,131016006001,Bengaluru,Full Stack Web Application (php) Developer,2.0,"1,75,000 - 2,50,000 P.A",2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,f22900298c591100e18a5cd63fad70d6,175000.0,250000.0,2.0,4.0
13,Mathematical Computing Software Company,UG: B.Tech/B.E. - Any Specialization PG:M.Tech...,3 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this * HDL...,131016003744,Bengaluru,Looking for an Application Engineer-fpga,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Other,5465aa5513846c4f392bb504b8f84052,NaN,NaN,3.0,8.0
14,Accenture,UG: Any Graduate - Any Specialization PG:MBA/P...,1 - 5 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Respo...,121016901343,Bengaluru,Revenue Assurance,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,4147417290df34c233b6f56829e548b0,NaN,NaN,1.0,5.0
15,PKS & Associates,"UG: B.Tech/B.E. - Any Specialization, BCA - Co...",5 - 7 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Senio...,121016900092,Bengaluru,Senior Java Full Stack Developer - Java/ Spring 4,2.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,ab05a90ab6715d8c729771267af820d4,NaN,NaN,5.0,7.0
16,SMACera Technologies Consulting and Services P...,NaN,1 - 2 yrs,Recruitment / Staffing,Job Description Send me Jobs like this 1. Hi...,30916001587,Bengaluru,Data Entry Executive,3.0,"1,00,000 - 2,00,000 P.A. incentives for achiev...",2016-10-13 16:20:55 +0000,NaN,Executive Assistant,46c420020318fa676659f1caadd7b898,100000.0,200000.0,1.0,2.0
17,Janak Vidya Consultancy Pvt. Ltd.,NaN,2 - 4 yrs,IT-Software / Software Services,Job Description Send me Jobs like this (2-3 ...,131016002831,Bengaluru,PHP Developer_banashankari II Stage,NaN,"1,00,000 - 5,00,000 P.A",2016-10-13 16:20:55 +0000,NaN,IT Software - Other,b8eda405502ff98ed50e5b0700fc2f13,100000.0,500000.0,2.0,4.0
18,Strivex Consulting Pvt Ltd,UG: Any Graduate - Any Specialization Doctorat...,5 - 10 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Bluet...,81016900140,Bengaluru,Bluetooth Host Software Development Engineer -...,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Mobile,551e04bc2bcb105eb1f6ad043213444f,NaN,NaN,5.0,10.0
19,Magna Infotech Pvt Ltd,UG: Any Graduate - Any Specialization PG:Any P...,0 - 1 yrs,Recruitment / Staffing,Job Description Send me Jobs like this Good ...,131016900573,Bengaluru,E-commerce Executive,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,ITES,8887c7f0d749387e4c864308b2c88237,NaN,NaN,0.0,1.0

In [241]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              21996 non-null  str
 1   education            20004 non-null  str
 2   experience           21996 non-null  str
 3   industry             21995 non-null  str
 4   jobdescription       21996 non-null  str
 5   jobid                22000 non-null  int64
 6   joblocation_address  21499 non-null  str
 7   jobtitle             22000 non-null  str
 8   numberofpositions    4464 non-null   float64
 9   payrate              21903 non-null  str
 10  postdate             21977 non-null  str
 11  site_name            3987 non-null   str
 12  skills               21472 non-null  str
 13  uniq_id              22000 non-null  str
 14  min_pay              4641 non-null   float64
 15  max_pay              4940 non-null   float64
 16  min_exp              21885 non-null  float64
 17  max_exp              21884 non-null  float64
dtypes: float64(5), int64(1), str(12)
memory usage: 3.0 MB

In [242]:
df["avg_pay"] = (df["min_pay"]+df["max_pay"])/2
df["avg_exp"] = (df["min_exp"]+df["max_exp"])/2

In [243]:
df.head(20)

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id,min_pay,max_pay,min_exp,max_exp,avg_pay,avg_exp
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8,150000.0,225000.0,0.0,1.0,187500.0,0.5
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0,0.0,0.0,200000.0,0.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN,4.0,8.0,NaN,6.0
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae,NaN,NaN,11.0,15.0,NaN,13.0
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4,NaN,NaN,6.0,8.0,NaN,7.0
5,PFS Web Global Services Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:MCA - ...,2 - 5 yrs,IT-Software / Software Services,Job Description Send me Jobs like this We ar...,131016005070,Bengaluru,WALK IN - As400 Developer - Pfsweb Global Serv...,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,8c3af9062ea835b0965779e2c7faac76,NaN,NaN,2.0,5.0,NaN,3.5
6,Kinesis Management Consultant Pvt. Ltd,NaN,1 - 3 yrs,IT-Software / Software Services,Job Description Send me Jobs like this exper...,131016004451,"Delhi NCR, Mumbai, Bengaluru, Kochi, Greater N...",PHP Developer,2.0,"3,00,000 - 6,50,000 P.A",2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,98f84958cd6409386e7f0c9e447b8510,300000.0,650000.0,1.0,3.0,475000.0,2.0
7,Agile HR consultancy Pvt. Ltd. hiring for Ross...,"UG: Diploma - Any Specialization, Electrical, ...",2 - 7 yrs,Aviation / Aerospace Firms,Job Description Send me Jobs like this Job D...,121016002995,Bengaluru,Member Technical Staff-wire Harness/cable Harn...,20.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Production,c811c10568fdbfdb3d5e633c99c914b4,NaN,NaN,2.0,7.0,NaN,4.5
8,HANSUM INDIA ELECTRONICS PVT.LTD.,"UG: Diploma - Any Specialization, Electronics/...",1 - 3 yrs,Industrial Products / Heavy Machinery,Job Description Send me Jobs like this Indep...,131016002120,Bengaluru,Team Leader,2.0,"1,00,000 - 2,00,000 P.A",2016-10-13 16:20:55 +0000,NaN,Production,a40cb270401af0c246dbe60dcf219262,100000.0,200000.0,1.0,3.0,150000.0,2.0
9,Accenture,UG: Any Graduate - Any Specialization PG:Any P...,1 - 5 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Overa...,121016901354,Bengaluru,German Translator,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,ITES,7774df1c672c0b92486da8b36a721638,NaN,NaN,1.0,5.0,NaN,3.0
10,Premium,UG: Any Graduate - Any Specialization PG:Any P...,1 - 3 yrs,FMCG / Foods / Beverage,Job Description Send me Jobs like this LimeT...,101016001508,"Mumbai, Delhi, Bengaluru",Business Development Manager,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Sales,8ad928aef950cd1bbc1c02d72898df47,NaN,NaN,1.0,3.0,NaN,2.0
11,Convate hiring for Retail/e-commerce domain,UG: Any Graduate - Any Specialization,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Greet...,61016003187,Bengaluru,Opening for Android Developer-bangalore-4-8 yrs,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,2657f737cb46cf289a05d6577a746976,NaN,NaN,4.0,8.0,NaN,6.0
12,Sinai Global,"UG: B.Tech/B.E. - Any Specialization, Diploma ...",2 - 4 yrs,IT-Software / Software Services,Job Description Send me Jobs like this We ar...,131016006001,Bengaluru,Full Stack Web Application (php) Developer,2.0,"1,75,000 - 2,50,000 P.A",2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,f22900298c591100e18a5cd63fad70d6,175000.0,250000.0,2.0,4.0,212500.0,3.0
13,Mathematical Computing Software Company,UG: B.Tech/B.E. - Any Specialization PG:M.Tech...,3 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this * HDL...,131016003744,Bengaluru,Looking for an Application Engineer-fpga,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Other,5465aa5513846c4f392bb504b8f84052,NaN,NaN,3.0,8.0,NaN,5.5
14,Accenture,UG: Any Graduate - Any Specialization PG:MBA/P...,1 - 5 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Respo...,121016901343,Bengaluru,Revenue Assurance,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,4147417290df34c233b6f56829e548b0,NaN,NaN,1.0,5.0,NaN,3.0
15,PKS & Associates,"UG: B.Tech/B.E. - Any Specialization, BCA - Co...",5 - 7 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Senio...,121016900092,Bengaluru,Senior Java Full Stack Developer - Java/ Spring 4,2.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,ab05a90ab6715d8c729771267af820d4,NaN,NaN,5.0,7.0,NaN,6.0
16,SMACera Technologies Consulting and Services P...,NaN,1 - 2 yrs,Recruitment / Staffing,Job Description Send me Jobs like this 1. Hi...,30916001587,Bengaluru,Data Entry Executive,3.0,"1,00,000 - 2,00,000 P.A. incentives for achiev...",2016-10-13 16:20:55 +0000,NaN,Executive Assistant,46c420020318fa676659f1caadd7b898,100000.0,200000.0,1.0,2.0,150000.0,1.5
17,Janak Vidya Consultancy Pvt. Ltd.,NaN,2 - 4 yrs,IT-Software / Software Services,Job Description Send me Jobs like this (2-3 ...,131016002831,Bengaluru,PHP Developer_banashankari II Stage,NaN,"1,00,000 - 5,00,000 P.A",2016-10-13 16:20:55 +0000,NaN,IT Software - Other,b8eda405502ff98ed50e5b0700fc2f13,100000.0,500000.0,2.0,4.0,300000.0,3.0
18,Strivex Consulting Pvt Ltd,UG: Any Graduate - Any Specialization Doctorat...,5 - 10 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Bluet...,81016900140,Bengaluru,Bluetooth Host Software Development Engineer -...,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Mobile,551e04bc2bcb105eb1f6ad043213444f,NaN,NaN,5.0,10.0,NaN,7.5
19,Magna Infotech Pvt Ltd,UG: Any Graduate - Any Specialization PG:Any P...,0 - 1 yrs,Recruitment / Staffing,Job Description Send me Jobs like this Good ...,131016900573,Bengaluru,E-commerce Executive,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,ITES,8887c7f0d749387e4c864308b2c88237,NaN,NaN,0.0,1.0,NaN,0.5

In [244]:
df.dtypes

company                    str
education                  str
experience                 str
industry                   str
jobdescription             str
jobid                    int64
joblocation_address        str
jobtitle                   str
numberofpositions      float64
payrate                    str
postdate                   str
site_name                  str
skills                     str
uniq_id                    str
min_pay                float64
max_pay                float64
min_exp                float64
max_exp                float64
avg_pay                float64
avg_exp                float64
dtype: object

#### Perform Feature Engineering on Postdate Feature

In [245]:
df["postdate"]

0        2016-05-21 19:30:00 +0000
1        2016-05-21 19:30:00 +0000
2        2016-10-13 16:20:55 +0000
3        2016-10-13 16:20:55 +0000
4        2016-10-13 16:20:55 +0000
                   ...
21995    2016-11-25 22:47:05 +0000
21996    2016-11-24 22:47:05 +0000
21997    2016-11-25 22:47:05 +0000
21998    2016-11-27 22:47:05 +0000
21999    2016-11-25 22:47:05 +0000
Name: postdate, Length: 22000, dtype: str

In [246]:
df["postdate"].dtype

In [247]:
pd.to_datetime(df["postdate"],errors="coerce")

0       2016-05-21 19:30:00+00:00
1       2016-05-21 19:30:00+00:00
2       2016-10-13 16:20:55+00:00
3       2016-10-13 16:20:55+00:00
4       2016-10-13 16:20:55+00:00
                   ...
21995   2016-11-25 22:47:05+00:00
21996   2016-11-24 22:47:05+00:00
21997   2016-11-25 22:47:05+00:00
21998   2016-11-27 22:47:05+00:00
21999   2016-11-25 22:47:05+00:00
Name: postdate, Length: 22000, dtype: datetime64[us, UTC]

In [248]:
df["postdate"]=pd.to_datetime(df["postdate"],errors="coerce")

In [249]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              21996 non-null  str
 1   education            20004 non-null  str
 2   experience           21996 non-null  str
 3   industry             21995 non-null  str
 4   jobdescription       21996 non-null  str
 5   jobid                22000 non-null  int64
 6   joblocation_address  21499 non-null  str
 7   jobtitle             22000 non-null  str
 8   numberofpositions    4464 non-null   float64
 9   payrate              21903 non-null  str
 10  postdate             21977 non-null  datetime64[us, UTC]
 11  site_name            3987 non-null   str
 12  skills               21472 non-null  str
 13  uniq_id              22000 non-null  str
 14  min_pay              4641 non-null   float64
 15  max_pay              4940 non-null   float64
 16  min_exp              21885 non-null  float64
 17  max_exp              21884 non-null  float64
 18  avg_pay              4640 non-null   float64
 19  avg_exp              21884 non-null  float64
dtypes: datetime64[us, UTC](1), float64(7), int64(1), str(11)
memory usage: 3.4 MB

In [250]:
df["year"] = df["postdate"].dt.year

In [251]:
df["month"] = df["postdate"].dt.month

In [252]:
df["day"] = df["postdate"].dt.day

In [253]:
df.head()

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,...,uniq_id,min_pay,max_pay,min_exp,max_exp,avg_pay,avg_exp,year,month,day
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",...,43b19632647068535437c774b6ca6cf8,150000.0,225000.0,0.0,1.0,187500.0,0.5,2016.0,5.0,21.0
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",...,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0,0.0,0.0,200000.0,0.0,2016.0,5.0,21.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,...,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN,4.0,8.0,NaN,6.0,2016.0,10.0,13.0
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,...,115d28f140f694dd1cc61c53d03c66ae,NaN,NaN,11.0,15.0,NaN,13.0,2016.0,10.0,13.0
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,...,a12553fc03bc7bcced8b1bb8963f97b4,NaN,NaN,6.0,8.0,NaN,7.0,2016.0,10.0,13.0

In [254]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              21996 non-null  str
 1   education            20004 non-null  str
 2   experience           21996 non-null  str
 3   industry             21995 non-null  str
 4   jobdescription       21996 non-null  str
 5   jobid                22000 non-null  int64
 6   joblocation_address  21499 non-null  str
 7   jobtitle             22000 non-null  str
 8   numberofpositions    4464 non-null   float64
 9   payrate              21903 non-null  str
 10  postdate             21977 non-null  datetime64[us, UTC]
 11  site_name            3987 non-null   str
 12  skills               21472 non-null  str
 13  uniq_id              22000 non-null  str
 14  min_pay              4641 non-null   float64
 15  max_pay              4940 non-null   float64
 16  min_exp              21885 non-null  float64
 17  max_exp              21884 non-null  float64
 18  avg_pay              4640 non-null   float64
 19  avg_exp              21884 non-null  float64
 20  year                 21977 non-null  float64
 21  month                21977 non-null  float64
 22  day                  21977 non-null  float64
dtypes: datetime64[us, UTC](1), float64(10), int64(1), str(11)
memory usage: 3.9 MB

#### Perform Feature Engineering on job_location Feature

In [255]:
df["joblocation_address"].value_counts().head(20)

joblocation_address
Bengaluru/Bangalore                                         3775
Mumbai                                                      2348
Bengaluru                                                   1453
Hyderabad / Secunderabad                                    1246
Chennai                                                     1204
Hyderabad                                                    936
Noida                                                        775
Delhi                                                        763
Gurgaon                                                      743
Mumbai , Mumbai                                              514
Delhi/NCR(National Capital Region)                           383
Bengaluru/Bangalore , Bengaluru / Bangalore                  360
Delhi , Delhi                                                324
Noida , Noida/Greater Noida                                  313
Gurgaon , Gurgaon                                            148
Bengaluru/Bangalore , Chennai , Hyderabad / Secunderabad     118
Ghaziabad                                                    102
Bengaluru/Bangalore , Hyderabad / Secunderabad               101
Bengaluru, Hyderabad                                          87
Delhi/NCR(National Capital Region) , Gurgaon                  83
Name: count, dtype: int64

In [256]:
data = df.copy()

In [257]:
pd.Series(data["joblocation_address"].unique())

0                                                 Chennai
1                                               Bengaluru
2       Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...
3       Delhi NCR, Mumbai, Bengaluru, Kochi, Greater N...
4                                Mumbai, Delhi, Bengaluru
                              ...
2325                           Mumbai, Bengaluru, Kolkata
2326                  Bengaluru, Pune, Chennai, Delhi NCR
2327                Mumbai, Bengaluru, Hyderabad, Kolkata
2328    Mumbai, Chennai, Delhi, Bengaluru, Hyderabad, ...
2329                                  Bengaluru, Malaysia
Length: 2330, dtype: str

In [258]:
#Top 60 cities that has more number of job location
data["joblocation_address"].value_counts().head(60).index

Index(['Bengaluru/Bangalore', 'Mumbai', 'Bengaluru',
       'Hyderabad / Secunderabad', 'Chennai', 'Hyderabad', 'Noida', 'Delhi',
       'Gurgaon', 'Mumbai , Mumbai', 'Delhi/NCR(National Capital Region)',
       'Bengaluru/Bangalore , Bengaluru / Bangalore', 'Delhi , Delhi',
       'Noida , Noida/Greater Noida', 'Gurgaon , Gurgaon',
       'Bengaluru/Bangalore , Chennai , Hyderabad / Secunderabad', 'Ghaziabad',
       'Bengaluru/Bangalore , Hyderabad / Secunderabad',
       'Bengaluru, Hyderabad', 'Delhi/NCR(National Capital Region) , Gurgaon',
       'Bengaluru/Bangalore , Chennai',
       'Bengaluru/Bangalore , Mumbai , Chennai , Pune , Hyderabad / Secunderabad , Delhi/NCR(National Capital Region) , Ahmedabad , Kolkata , Surat',
       'Bengaluru/Bangalore , karnataka',
       'Delhi , Delhi/NCR(National Capital Region)',
       'Chennai , Hyderabad / Secunderabad',
       'Hyderabad / Secunderabad , Hyderabad/Secunderabad',
       'Delhi/NCR(National Capital Region) , Noida',
       'Bengaluru, Chennai, Hyderabad', 'Navi Mumbai', 'Mumbai , Navi Mumbai',
       'Mumbai , mumbai', 'Hyderabad, Bengaluru', 'Faridabad',
       'Chennai , Bengaluru/Bangalore', 'Mumbai , Pune',
       'Bengaluru, Hyderabad, Chennai',
       'Hyderabad / Secunderabad , Bengaluru/Bangalore',
       'Bengaluru/Bangalore , Mumbai', 'Mumbai, Bengaluru',
       'Bengaluru/Bangalore , Chennai , Noida , Hyderabad / Secunderabad',
       'Bengaluru/Bangalore , Mumbai , Chennai', 'Bengaluru, Chennai',
       'Delhi , Mumbai',
       'Bengaluru/Bangalore , Bengaluru / Bangalore , Delhi , Mumbai',
       'Bengaluru/Bangalore , Mumbai , Delhi/NCR(National Capital Region)',
       'Delhi , Delhi/NCR', 'Bengaluru Bangalore',
       'Bengaluru/Bangalore , Gurgaon',
       'Bengaluru/Bangalore , Hyderabad / Secunderabad , Delhi/NCR(National Capital Region)',
       'Gurgaon , Delhi/NCR(National Capital Region)', 'Mumbai, maharashtra',
       'Mumbai , Hyderabad / Secunderabad , Guwahati , Bhubaneshwar , Raipur , Chandigarh',
       'Delhi/NCR(National Capital Region) , Gurgaon , Noida',
       'Bengaluru/Bangalore , bangalore',
       'Bengaluru/Bangalore , Bengaluru / Bangalore , Mumbai',
       'Bengaluru/Bangalore , Bengaluru / Bangalore , Delhi',
       'Delhi/NCR(National Capital Region) , Delhi',
       'Hyderabad / Secunderabad , Chennai',
       'Bengaluru/Bangalore , Hyderabad / Secunderabad , Chennai',
       'Noida , Bengaluru/Bangalore'],
      dtype='str', name='joblocation_address')

In [259]:
replacement = pd.read_csv(r"C:\WORK\Data Analysis Projects\Job Market Data Analysis Project (Naukari.com)\Datasets\replacements.csv").set_index("Unnamed: 0")

In [260]:
replacement

                                                   joblocation_address
Unnamed: 0
 Delhi/NCR(National Capital Region)                              Delhi
 Delhi/NCR(National Capital Region)                              Delhi
(Bengaluru/Bangalore)                                        Bangalore
Bangalore                                                    Bangalore
Bangalore , Bangalore / Bangalore                            Bangalore
Bangalore Bangalore                                          Bangalore
Bangalore,Bangalore / Bangalore                              Bangalore
Bangalore,karnataka                                          Bangalore
Bengaluru                                                    Bangalore
Bengaluru/Bangalore                                          Bangalore
Bengaluru/Bangalore , bangalore                              Bangalore
DELHI(NATIONAL CAPITAL REGION)                                   Delhi
Delhi                                                            Delhi
Delhi , Delhi                                                    Delhi
Delhi , Delhi/Greater Delhi                                      Delhi
Delhi , Delhi/NCR(National Capital Region)                       Delhi
Delhi NCR                                                        Delhi
Delhi(National Capital Region)                                   Delhi
Delhi(National Capital Region) , Delhi                           Delhi
Delhi,Delhi                                                      Delhi
Delhi/NCR                                                        Delhi
Delhi/NCR(National Capital Region)                               Delhi
Delhi/NCR(National Capital Region)                               Delhi
Delhi/NCR(National Capital Region) , Delhi                       Delhi
Delhi/NCR(National Capital Region) , Gurgaon , ...               Delhi
Delhi/NCR(National Capital Region) , Noida                       Delhi
Delhi/NCR(National Capital Region),Gurgaon                       Delhi
Ghaziabad                                                        Delhi
Gurgaon                                                          Delhi
Gurgaon , Delhi/NCR(National Capital Region)                     Delhi
Gurgaon , Gurgaon                                                Delhi
Hyderabad / Secunderabad                                     Hyderabad
Hyderabad / Secunderabad , Hyderabad/Secunderabad            Hyderabad
Mumbai , Mumbai                                                 Mumbai
Mumbai, maharashtra                                             Mumbai
NCR,NCR                                                          Delhi
Noida                                                            Delhi
Noida , Noida/Greater Noida                                      Delhi
Noida/Greater Noida                                              Delhi

In [261]:
replacement_dict = replacement.to_dict()

In [262]:
data.replace(replacement_dict,inplace=True,regex=True)

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,...,uniq_id,min_pay,max_pay,min_exp,max_exp,avg_pay,avg_exp,year,month,day
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",...,43b19632647068535437c774b6ca6cf8,150000.0,225000.0,0.0,1.0,187500.0,0.5,2016.0,5.0,21.0
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",...,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0,0.0,0.0,200000.0,0.0,2016.0,5.0,21.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bangalore,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,...,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN,4.0,8.0,NaN,6.0,2016.0,10.0,13.0
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bangalore, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,...,115d28f140f694dd1cc61c53d03c66ae,NaN,NaN,11.0,15.0,NaN,13.0,2016.0,10.0,13.0
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bangalore,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,...,a12553fc03bc7bcced8b1bb8963f97b4,NaN,NaN,6.0,8.0,NaN,7.0,2016.0,10.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21995,Morgan Stanley Advantage Services Pvt. Ltd.,UG: Any Graduate - Any Specialization,9 - 13 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this Greet...,241116007152,Bangalore,Quality Assurance - VP with Morgan Stanley Ban...,2.0,Not Disclosed by Recruiter,...,ef40136e3b0c0abdab695d979a4b7153,NaN,NaN,9.0,13.0,NaN,11.0,2016.0,11.0,25.0
21996,Careernet Technologies Pvt Ltd hiring for Client,UG: B.Tech/B.E. - Any Specialization PG:M.Tech...,3 - 5 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Looki...,241116001104,"Bangalore, Delhi",Java Backend Developers for a Product Company,NaN,"8,50,000 - 14,00,000 P.A",...,acb80b7bb109fa76d22d1f11c6e16c6a,850000.0,1400000.0,3.0,5.0,1125000.0,4.0,2016.0,11.0,24.0
21997,Musk - Startup,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,2 - 4 yrs,Internet / Ecommerce,Job Description Send me Jobs like this Work ...,251116900644,Bangalore,Full Stack Development Engineer,NaN,Not Disclosed by Recruiter,...,f6f2885a6c87572616fb766029a0d284,NaN,NaN,2.0,4.0,NaN,3.0,2016.0,11.0,25.0
21998,Confidential,UG: B.Tech/B.E. - Any Specialization PG:MCA - ...,7 - 12 yrs,IT-Software / Software Services,Job Description Send me Jobs like this We ar...,231116901329,"Delhi, Bangalore",Sr UI Developer/ Technical Lead - Html/ CSS/ J...,NaN,Not Disclosed by Recruiter,...,c6f6538cb1007dd02c1b4b77909b3d38,NaN,NaN,7.0,12.0,NaN,9.5,2016.0,11.0,27.0
21999,Cambio Consulting India Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:MCA - ...,5 - 10 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Job d...,251116003840,Bangalore,RF Firmware Engineers,NaN,"12,00,000 - 22,00,000 P.A",...,74fec26df6e1c0be0171311a2f03f180,1200000.0,2200000.0,5.0,10.0,1700000.0,7.5,2016.0,11.0,25.0

In [263]:
data["joblocation_address"].value_counts()

joblocation_address
Bangalore                                             5228
Mumbai                                                2887
Delhi                                                 2741
Hyderabad                                             2182
Chennai                                               1204
                                                      ...
Mumbai, Bangalore, Kolkata                               1
Bangalore, Pune, Chennai, Delhi                          1
Mumbai, Bangalore, Hyderabad, Kolkata                    1
Mumbai, Chennai, Delhi, Bangalore, Hyderabad, Pune       1
Bangalore, Malaysia                                      1
Name: count, Length: 2141, dtype: int64

In [264]:
# initial we have only 3775 in banglore job location, but now its 5228
df["joblocation_address"].value_counts().head(10)

joblocation_address
Bengaluru/Bangalore         3775
Mumbai                      2348
Bengaluru                   1453
Hyderabad / Secunderabad    1246
Chennai                     1204
Hyderabad                    936
Noida                        775
Delhi                        763
Gurgaon                      743
Mumbai , Mumbai              514
Name: count, dtype: int64

In [265]:
data.head(3)

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,...,uniq_id,min_pay,max_pay,min_exp,max_exp,avg_pay,avg_exp,year,month,day
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",...,43b19632647068535437c774b6ca6cf8,150000.0,225000.0,0.0,1.0,187500.0,0.5,2016.0,5.0,21.0
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",...,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0,0.0,0.0,200000.0,0.0,2016.0,5.0,21.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bangalore,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,...,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN,4.0,8.0,NaN,6.0,2016.0,10.0,13.0

In [266]:
data.columns

Index(['company', 'education', 'experience', 'industry', 'jobdescription',
       'jobid', 'joblocation_address', 'jobtitle', 'numberofpositions',
       'payrate', 'postdate', 'site_name', 'skills', 'uniq_id', 'min_pay',
       'max_pay', 'min_exp', 'max_exp', 'avg_pay', 'avg_exp', 'year', 'month',
       'day'],
      dtype='str')

In [267]:
def drop_feature(column):
    data.drop(column,axis=1,inplace=True)

In [268]:
drop_feature("payrate")

In [269]:
drop_feature("experience")
drop_feature("postdate")
drop_feature("uniq_id")

In [270]:
data.columns

Index(['company', 'education', 'industry', 'jobdescription', 'jobid',
       'joblocation_address', 'jobtitle', 'numberofpositions', 'site_name',
       'skills', 'min_pay', 'max_pay', 'min_exp', 'max_exp', 'avg_pay',
       'avg_exp', 'year', 'month', 'day'],
      dtype='str')

In [271]:
data.to_csv(r"../Datasets/Updated_datasets/naukri_data2.csv",index=False)