In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("Import all the libraries")

Import all the libraries

In [2]:
DATA_DIR = r"C:\WORK\Data Analysis Projects\Job Market Data Analysis Project (Naukari.com)\Datasets\naukri_com-job_sample.csv"

In [3]:
df=pd.read_csv(DATA_DIR)

In [5]:
df.head()

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4

In [6]:
df.shape

(22000, 14)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              21996 non-null  str
 1   education            20004 non-null  str
 2   experience           21996 non-null  str
 3   industry             21995 non-null  str
 4   jobdescription       21996 non-null  str
 5   jobid                22000 non-null  int64
 6   joblocation_address  21499 non-null  str
 7   jobtitle             22000 non-null  str
 8   numberofpositions    4464 non-null   float64
 9   payrate              21903 non-null  str
 10  postdate             21977 non-null  str
 11  site_name            3987 non-null   str
 12  skills               21472 non-null  str
 13  uniq_id              22000 non-null  str
dtypes: float64(1), int64(1), str(12)
memory usage: 2.3 MB

In [8]:
df.isnull().sum()

company                    4
education               1996
experience                 4
industry                   5
jobdescription             4
jobid                      0
joblocation_address      501
jobtitle                   0
numberofpositions      17536
payrate                   97
postdate                  23
site_name              18013
skills                   528
uniq_id                    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [12]:
missing_values = df.isnull().sum()

missing_values

company                    4
education               1996
experience                 4
industry                   5
jobdescription             4
jobid                      0
joblocation_address      501
jobtitle                   0
numberofpositions      17536
payrate                   97
postdate                  23
site_name              18013
skills                   528
uniq_id                    0
dtype: int64

In [16]:
percentage_missing = missing_values*100/len(df)
percentage_missing

company                 0.018182
education               9.072727
experience              0.018182
industry                0.022727
jobdescription          0.018182
jobid                   0.000000
joblocation_address     2.277273
jobtitle                0.000000
numberofpositions      79.709091
payrate                 0.440909
postdate                0.104545
site_name              81.877273
skills                  2.400000
uniq_id                 0.000000
dtype: float64

In [18]:
missing_values_df = pd.DataFrame({"Count_Missing":missing_values,
                                  "Percentage_Missing":percentage_missing})

In [19]:
missing_values_df

                     Count_Missing  Percentage_Missing
company                          4            0.018182
education                     1996            9.072727
experience                       4            0.018182
industry                         5            0.022727
jobdescription                   4            0.018182
jobid                            0            0.000000
joblocation_address            501            2.277273
jobtitle                         0            0.000000
numberofpositions            17536           79.709091
payrate                         97            0.440909
postdate                        23            0.104545
site_name                    18013           81.877273
skills                         528            2.400000
uniq_id                          0            0.000000

In [23]:
df.columns

Index(['company', 'education', 'experience', 'industry', 'jobdescription',
       'jobid', 'joblocation_address', 'jobtitle', 'numberofpositions',
       'payrate', 'postdate', 'site_name', 'skills', 'uniq_id'],
      dtype='str')

In [57]:
for col in df.columns:
    print("{} has {} values".format(col,df[col].nunique()))

company has 8469 values
education has 2355 values
experience has 147 values
industry has 63 values
jobdescription has 21063 values
jobid has 21910 values
joblocation_address has 2329 values
jobtitle has 17564 values
numberofpositions has 84 values
payrate has 1848 values
postdate has 4203 values
site_name has 1 values
skills has 45 values
uniq_id has 22000 values

In [60]:
unique = []

for col in df.columns:
    unique.append([col,df[col].nunique(),df[col].unique])

In [61]:
unique

[['company',
  8469,
  <bound method Series.unique of 0                                        MM Media Pvt Ltd
  1                                      find live infotech
  2                     Softtech Career Infosystem Pvt. Ltd
  3                                  Onboard HRServices LLP
  4              Spire Technologies and Solutions Pvt. Ltd.
                                 ...
  21995         Morgan Stanley Advantage Services Pvt. Ltd.
  21996    Careernet Technologies Pvt Ltd hiring for Client
  21997                                      Musk - Startup
  21998                                        Confidential
  21999                     Cambio Consulting India Pvt Ltd
  Name: company, Length: 22000, dtype: str>],
 ['education',
  2355,
  <bound method Series.unique of 0        UG: B.Tech/B.E. - Any Specialization PG:Any Po...
  1        UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...
  2        UG: Any Graduate - Any Specialization PG:Any P...
  3        UG: Any Graduate - Any Specialization PG:CA Do...
  4        UG: B.Tech/B.E. - Any Specialization PG:Any Po...
                                 ...
  21995                UG: Any Graduate - Any Specialization
  21996    UG: B.Tech/B.E. - Any Specialization PG:M.Tech...
  21997    UG: B.Tech/B.E. - Any Specialization PG:Any Po...
  21998    UG: B.Tech/B.E. - Any Specialization PG:MCA - ...
  21999    UG: B.Tech/B.E. - Any Specialization PG:MCA - ...
  Name: education, Length: 22000, dtype: str>],
 ['experience',
  147,
  <bound method Series.unique of 0          0 - 1 yrs
  1          0 - 0 yrs
  2          4 - 8 yrs
  3        11 - 15 yrs
  4          6 - 8 yrs
              ...
  21995     9 - 13 yrs
  21996      3 - 5 yrs
  21997      2 - 4 yrs
  21998     7 - 12 yrs
  21999     5 - 10 yrs
  Name: experience, Length: 22000, dtype: str>],
 ['industry',
  63,
  <bound method Series.unique of 0                Media / Entertainment / Internet
  1        Advertising / PR / MR / Event Management
  2                 IT-Software / Software Services
  3          Banking / Financial Services / Broking
  4                 IT-Software / Software Services
                             ...
  21995      Banking / Financial Services / Broking
  21996             IT-Software / Software Services
  21997                        Internet / Ecommerce
  21998             IT-Software / Software Services
  21999             IT-Software / Software Services
  Name: industry, Length: 22000, dtype: str>],
 ['jobdescription',
  21063,
  <bound method Series.unique of 0        Job Description   Send me Jobs like this Quali...
  1        Job Description   Send me Jobs like this Quali...
  2        Job Description   Send me Jobs like this - as ...
  3        Job Description   Send me Jobs like this - Inv...
  4        Job Description   Send me Jobs like this Pleas...
                                 ...
  21995    Job Description   Send me Jobs like this Greet...
  21996    Job Description   Send me Jobs like this Looki...
  21997    Job Description   Send me Jobs like this Work ...
  21998    Job Description   Send me Jobs like this We ar...
  21999    Job Description   Send me Jobs like this Job d...
  Name: jobdescription, Length: 22000, dtype: str>],
 ['jobid',
  21910,
  <bound method Series.unique of 0        210516002263
  1        210516002391
  2        101016900534
  3         81016900536
  4        120916002122
               ...
  21995    241116007152
  21996    241116001104
  21997    251116900644
  21998    231116901329
  21999    251116003840
  Name: jobid, Length: 22000, dtype: int64>],
 ['joblocation_address',
  2329,
  <bound method Series.unique of 0                                                  Chennai
  1                                                  Chennai
  2                                                Bengaluru
  3        Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...
  4                                                Bengaluru
                                 ...
  21995                                            Bengaluru
  21996                                   Bengaluru, Gurgaon
  21997                                            Bengaluru
  21998                                 Delhi NCR, Bengaluru
  21999                                            Bengaluru
  Name: joblocation_address, Length: 22000, dtype: str>],
 ['jobtitle',
  17564,
  <bound method Series.unique of 0                 Walkin Data Entry Operator (night Shift)
  1                       Work Based Onhome Based Part Time.
  2                                   Pl/sql Developer - SQL
  3                   Manager/ad/partner - Indirect Tax - CA
  4                          JAVA Technical Lead (6-8 yrs) -
                                 ...
  21995    Quality Assurance - VP with Morgan Stanley Ban...
  21996        Java Backend Developers for a Product Company
  21997                      Full Stack Development Engineer
  21998    Sr UI Developer/ Technical Lead - Html/ CSS/ J...
  21999                                RF Firmware Engineers
  Name: jobtitle, Length: 22000, dtype: str>],
 ['numberofpositions',
  84,
  <bound method Series.unique of 0         NaN
  1        60.0
  2         NaN
  3         NaN
  4         4.0
           ...
  21995     2.0
  21996     NaN
  21997     NaN
  21998     NaN
  21999     NaN
  Name: numberofpositions, Length: 22000, dtype: float64>],
 ['payrate',
  1848,
  <bound method Series.unique of 0               1,50,000 - 2,25,000 P.A
  1        1,50,000 - 2,50,000 P.A. 20000
  2            Not Disclosed by Recruiter
  3            Not Disclosed by Recruiter
  4            Not Disclosed by Recruiter
                        ...
  21995        Not Disclosed by Recruiter
  21996          8,50,000 - 14,00,000 P.A
  21997        Not Disclosed by Recruiter
  21998        Not Disclosed by Recruiter
  21999         12,00,000 - 22,00,000 P.A
  Name: payrate, Length: 22000, dtype: str>],
 ['postdate',
  4203,
  <bound method Series.unique of 0        2016-05-21 19:30:00 +0000
  1        2016-05-21 19:30:00 +0000
  2        2016-10-13 16:20:55 +0000
  3        2016-10-13 16:20:55 +0000
  4        2016-10-13 16:20:55 +0000
                     ...
  21995    2016-11-25 22:47:05 +0000
  21996    2016-11-24 22:47:05 +0000
  21997    2016-11-25 22:47:05 +0000
  21998    2016-11-27 22:47:05 +0000
  21999    2016-11-25 22:47:05 +0000
  Name: postdate, Length: 22000, dtype: str>],
 ['site_name',
  1,
  <bound method Series.unique of 0                   NaN
  1                   NaN
  2                   NaN
  3                   NaN
  4                   NaN
                ...
  21995    www.naukri.com
  21996    www.naukri.com
  21997    www.naukri.com
  21998    www.naukri.com
  21999    www.naukri.com
  Name: site_name, Length: 22000, dtype: str>],
 ['skills',
  45,
  <bound method Series.unique of 0                                         ITES
  1                                    Marketing
  2        IT Software - Application Programming
  3                                     Accounts
  4        IT Software - Application Programming
                           ...
  21995               IT Software - QA & Testing
  21996    IT Software - Application Programming
  21997    IT Software - Application Programming
  21998    IT Software - Application Programming
  21999         IT Software - System Programming
  Name: skills, Length: 22000, dtype: str>],
 ['uniq_id',
  22000,
  <bound method Series.unique of 0        43b19632647068535437c774b6ca6cf8
  1        d4c72325e57f89f364812b5ed5a795f0
  2        c47df6f4cfdf5b46f1fd713ba61b9eba
  3        115d28f140f694dd1cc61c53d03c66ae
  4        a12553fc03bc7bcced8b1bb8963f97b4
                         ...
  21995    ef40136e3b0c0abdab695d979a4b7153
  21996    acb80b7bb109fa76d22d1f11c6e16c6a
  21997    f6f2885a6c87572616fb766029a0d284
  21998    c6f6538cb1007dd02c1b4b77909b3d38
  21999    74fec26df6e1c0be0171311a2f03f180
  Name: uniq_id, Length: 22000, dtype: str>]]

In [63]:
unique_df = [[col,df[col].nunique(),df[col].unique()] for col in df.columns]

In [64]:
pd.DataFrame(unique_df,columns=["col_name","count","unique"])

,col_name,count,unique
0,company,8469,"[MM Media Pvt Ltd, find live infotech, Softtec..."
1,education,2355,[UG: B.Tech/B.E. - Any Specialization PG:Any P...
2,experience,147,"[0 - 1 yrs, 0 - 0 yrs, 4 - 8 yrs, 11 - 15 yrs,..."
3,industry,63,"[Media / Entertainment / Internet, Advertising..."
4,jobdescription,21063,[Job Description Send me Jobs like this Qual...
5,jobid,21910,"[210516002263, 210516002391, 101016900534, 810..."
6,joblocation_address,2329,"[Chennai, Bengaluru, Mumbai, Bengaluru, Kolkat..."
7,jobtitle,17564,"[Walkin Data Entry Operator (night Shift), Wor..."
8,numberofpositions,84,"[nan, 60.0, 4.0, 2.0, 20.0, 3.0, 1.0, 700.0, 8..."
9,payrate,1848,"[1,50,000 - 2,25,000 P.A, 1,50,000 - 2,50,000 ..."
10,postdate,4203,"[2016-05-21 19:30:00 +0000, 2016-10-13 16:20:5..."
11,site_name,1,"[nan, www.naukri.com]"
12,skills,45,"[ITES, Marketing, IT Software - Application Pr..."
13,uniq_id,22000,"[43b19632647068535437c774b6ca6cf8, d4c72325e57..."

In [65]:
df.columns

Index(['company', 'education', 'experience', 'industry', 'jobdescription',
       'jobid', 'joblocation_address', 'jobtitle', 'numberofpositions',
       'payrate', 'postdate', 'site_name', 'skills', 'uniq_id'],
      dtype='str')

In [66]:
df["payrate"]

0               1,50,000 - 2,25,000 P.A
1        1,50,000 - 2,50,000 P.A. 20000
2            Not Disclosed by Recruiter
3            Not Disclosed by Recruiter
4            Not Disclosed by Recruiter
                      ...
21995        Not Disclosed by Recruiter
21996          8,50,000 - 14,00,000 P.A
21997        Not Disclosed by Recruiter
21998        Not Disclosed by Recruiter
21999         12,00,000 - 22,00,000 P.A
Name: payrate, Length: 22000, dtype: str